language: python
python:
 - "2.7"
install:
 - "sudo add-apt-repository -y ppa:nilya/couchdb-1.3"
 - "sudo apt-get update"
 - "sudo apt-get install -qq -y couchdb"
 - "sudo cp .travis/local.ini /etc/couchdb/local.ini"
 - "sudo service couchdb restart"
 - "sudo service couchdb status"
 - "sleep 3"
 - "sudo service couchdb status"
script: "curl http://127.0.0.1:5984/"
services:
 - couchdb
